import './css/style.css'

import {Architects_Daughter, Bebas_Neue } from 'next/font/google'

import Header from '@/components/ui/header'
import Banner from '@/components/banner'

/*({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap'
})*/

const bebas_neue = Bebas_Neue({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-bebas-neue',
  display: 'swap'
})

const architects_daughter = Architects_Daughter({
  subsets: ['latin'],
  variable: '--font-architects-daughter',
  weight: '400',
  display: 'swap'
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${bebas_neue.variable} ${architects_daughter.variable} font-bebas neue bg-gray-900 text-gray-200 tracking-tight`}>
        <div className="flex flex-col min-h-screen overflow-hidden">
          <Header />
          {children}
          <Banner />
        </div>
      </body>
    </html>
  )
}
 