name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:

  build:

    runs-on: self-hosted

    steps:
    - name: Pull Docker image
      run: sudo docker pull saucotec/open-react-saucotec:latest
    - name: Delete Old docker container
      run: sudo docker rm -f open-react-saucotec-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 3005:3005 --name open-react-saucotec-container saucotec/open-react-saucotec