name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: "tu_nombre_de_usuario"
        DOCKER_PASSWORD: "tu_contraseña"
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker build -t varsubham/cicd-pipeline .
    - name: Push to Dockerhub
      run: docker push varsubham/cicd-pipeline:latest
