name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: "saucotec"
        DOCKER_PASSWORD: "Doeest822!"
      run: sudo docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: sudo docker build -t open-react-saucotec .
    - name: Push to Dockerhub
      run: sudo docker push totobece/open-react-saucotec:latest
